# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment # deployment name
  labels:
    name: auth-deployment
  namespace: dev-namespace # namespace
spec:
  replicas: 3 # number of replicas
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - name: auth-container
        image: localhost:5000/auth:latest
        ports:
        - containerPort: 80 # container port
        resources:
          requests:
            cpu: "100m"        # Reserve 0.1 CPU
            memory: "128Mi"    # Reserve 128 MiB
          limits:
            cpu: "500m"        # Hard cap at 0.5 CPU
            memory: "256Mi"    # Hard cap at 256 MiB
