apiVersion: v1
kind: Service
metadata:
  name: auth-service # Service name
  namespace: dev-namespace # namespace
spec:
  selector:
    app: auth-deployment # Selector to match pods
  type: LoadBalancer # Service type
  ports:
  - name: http # Port name
    protocol: TCP # Protocol
    targetPort: 8080 # Target port on the pod
    port: 3000 # Service port External (http://127.0.0.1:3000)
